### ISSUE TITLE
Additional Pen Data and Compatability

### ISSUE THREAD

**Issue by skibulk** [kevinb7/wacom_chrome_app#1]
Is it possible to get pen tilt and rotation values using native messaging? Are intuos pro tablets and cintiq display monitors supported? Does this work on Windows and Mac? Thanks!

**Comment by skibulk** [comment]
I went to "chrome://extensions/" and selected "Load Unpacked Extension..." where I successfully installed your "chrome_app" source folder. I restarted Chrome and launched the app. A color picker is displayed over a green background, however my pen does nothing on the canvas. The chrome inspector does not report any errors. I am using a Wacom Cintiq 22HD Touch, Wacom Driver Version 6.3.15-1, Chrome Version 46.0.2490.80 m, and Windows 7 Pro 64 Bit.

**Comment by skibulk** [comment]
I noticed that you are calling "chrome.runtime.connectNative('com.kevinb.wacom')". This repository seems to be missing the "com.kevinb.wacom" script?

**Comment by k4b7** [comment]
This project only works on Mac OS X.  There's a .m (Objective-C) that needs to be compiled and run which ferries events from the OS directly to the extension using a Chrome API that can talk directly to external processes via stdin/stdout.  Since you're on Windows I would suggest using IE/Edge for a browser and using the PointerEvent interface: http://www.w3.org/TR/pointerevents/#pointerevent-interface.  http://www.w3.org/TR/pointerevents/#pointerevent-interface
